name: Deploy Augur Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build          # Vite outputs to dist/

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v3
        with:
          # token already injected by az cli create (or add manually in repo > Settings > Secrets)
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

          # path to built files
          app_location: .
          output_location: dist
